### ISSUE TITLE
👍❓アイコンの横に数字が表示される仕組み

### ISSUE THREAD

**Issue by naoyatk** [sn6t/jgs2020-ip024#1]
[いいね][わからない]が押されたら、テキスト行が追加で出るのではなく、アイコンの横に数字が表示されて、それがカウントアップされていくような仕組みにすることは可能か。以下イメージ画像（参考：Discordのリアクション機能）。
[https://cdn.discordapp.com/attachments/580398425825083404/722435612535291954/SnapCrab_NoName_2020-6-16_22-0-54_No-00.png](url)

**Comment by sn6t** [comment]
👍ボタンや❓ボタンを押した時の挙動としては、一番最初に考えていたのはこの方式です。一番最初に考えていたのにこうしていないのは、ちゃんと考えてからでないと実装出来なさそうなためです（とりあえずの妥協案として音声テキストと同じ様にメッセージ表示をするようにしたというのが2020年2月18日の話）。

ローカル画面上で👍ボタンを押す度に数字をカウントアップすることは簡単にできますが、このアプリケーションの場合、他の人の画面上でもそのカウントアップ結果が反映されていく必要があります。ではそれはどうやると実現出来るのか？というのがnaoyatkさんへの宿題です。

**Comment by sn6t** [comment]
dev環境に反映し、6月18日検証でも問題ないということでmasterブランチにマージしました。クローズします。
